nexforce/script-automation

hubspot/custom-code/customUsersRRBind.js
-O objetivo desse código é criar uma nova lógica de round robin baseado agora em usuários, fazendo com que seja igualitária a distribuição de novos usuários;
- `customUsersRRBind.js`: nesse arquivo foi adicionada nova lógica de distribuição de owner;
- Qualquer informação extra referenciada em [Task Bind](https://app.clickup.com/t/86a2jaqfg);
=> [Task Bind] Change distribution code to generate an equitable distribution

hubspot/custom-code/customDeleteTasks.js
O objetivo da tarefa era criar um script que deleta as tasks quando o Lead se torna lost, opportunitie ou won.
- `customDeleteTasks.js`: Nesse arquivo foi incluído o script que faz a tarefa mencionada acima.
Qualquer informação adicional em [Task](https://app.clickup.com/t/86a29ah2d). O WF foi baseado em [Python](https://app.hubspot.com/workflows/24325742/platform/flow/565463910/edit) e desenvolvido em [JS](https://app.hubspot.com/workflows/24325742/platform/flow/565692832/edit)
=> [Otimização] Atualizar atividades de Sequência de No-Show

hubspot/custom-code/js/customAssociationCartDeal.js
A tarefa tinha como objetivo revisar e corrigir um custom code responsável pela associação entre carrinho e deal a partir do id do carrinho vindo da deal do Salesforce.
- `customAssociationCartDeal.js`: Aqui foi adicionada a função responsável por realizar o objetivo acima.
- Qualquer informação adicional em [Task](https://app.clickup.com/t/86a1k9vjv)
=> [Desenvolvimento] Habilitar e ajustar Workflows de sincronização Salesforce

hubspot/custom-code/js/customAssignOwnerByAssessorCode.js, hubspot/custom-code/js/customAssignOwnerByTeam.js, hubspot/custom-code/js/customCaptureCampaign.js, hubspot/custom-code/js/customCaptureCampaignByPartner.js, hubspot/custom-code/js/customConversionCampaignInfoSet.js, hubspot/custom-code/js/customCurrentCampaignInfoSet.js, hubspot/custom-code/js/customDealAssociationToPromotion.js, hubspot/custom-code/js/customManualSalesIndication.js, hubspot/custom-code/js/customRecaptureCampaign.js
Adicionados workflows utilizados na conta Nomos, tal como descrito na tarefa: https://app.clickup.com/t/86a3b0y9x
=> HubSpot Custom Code backups

hubspot/custom-code/js/customCaptureCampaignByPartner.js, hubspot/custom-code/js/customEcomGetAnalisys.js, hubspot/custom-code/js/customEcomSendAnalisysFirst.js, hubspot/custom-code/js/customEcomSendAnalisysSecond.js, hubspot/custom-code/js/customEcomSendFile.js, hubspot/custom-code/js/customReferralCountIncrease.js
Esse conjunto de códigos como um todo visa solucionar uma regra de negócio pedida pelo cliente que se divide em etapas. Primeiro é feito o envio de um pdf que contém dados de fatura para uma API de parse, esses dados são consumidos e utlizados no preenchimento do objeto Unidade Consumidora. Por último é enviado o documento (CPF ou CNPJ) para análise de crédito em outra API, essa análise retornam dados importantes para tomada de decisão.
- `hubspot/custom-code/js/customEcomSendFile.js`: Código customizado que envia a fatura e recebe os dados.
- `hubspot/custom-code/js/customEcomSendAnalisysFirst.js`: Código customizado que envia a primeira análise de crédito.
- `hubspot/custom-code/js/customEcomSendAnalisysSecond.js`: Código customizado que envia a segunda análise de crédito para CNPJ.
- …
=> feat: added new custom codes for client: ECOM

hubspot/custom-code/js/customHs>SAP.js
Tarefa tem como objetivo desenvolver um custom code que faz a comunicação via API com a plataforma SAP C4C. Ele é responsável por criar novos leads dentro do SAP a partir de contatos na Hub.
- `hubspot/custom-code/js/customHs>SAP.js`: Código desenvolvido para essa funcionalidade.
Qualquer outra informação adicional em [task](https://app.clickup.com/t/86a2tf711).
=> [Desenvolvimento] Workflow de envio de dados SAP

hubspot/custom-code/js/customRocketSeatPhone.js
O custom code tem como objetivo solucionar o problema de incompatibilidade de telefone de whatsapp registrado na plataforma e na hubspot. Além de atualizar o número de telefone com aquele que vem diretamente da mensagem, ele associa o novo ticket ao contato correto, garantindo assim a rastreabilidade das informações.
-`hubspot/custom-code/js/customRocketSeatPhone.js`: Aqui foi criado o custom code para isso.
Qualquer informação adicional favor validar diretamente na [tarefa](https://app.clickup.com/t/86a3gavj3).
=> [Desenvolvimento] Validação e blindagem para conversas de Whatsapp (9º digito)

hubspot/custom-code/js/Client-Specific-Codes/Pipefy/customApolloContactEnrhicment.js
added api call to apollo for leads data enrichment
=> Create custom code for Apollo integration

hubspot/custom-code/js/Client-Specific-Codes/SGA/customGetTicketByThreadId.js, hubspot/custom-code/js/Client-Specific-Codes/SGA/customGiveAnOwnerToThread.js
Desenvolver um código customizado que reatribua automaticamente chats sem owner, quando a capacidade máxima de atendentes for atingida.
``hubspot/custom-code/js/Client-Specific-Codes/SGA/customGetTicketByThreadId.js: Aqui o código busca uma thread pelo id e retorna sua área de atendimento.
`hubspot/custom-code/js/Client-Specific-Codes/SGA/customGiveAnOwnerToThread.js`: Aqui é feita uma valiação de disponibilidade de agentes e selecionado o email daquele que está disponível
Qualquer informação adicional em [task](https://app.clickup.com/t/86a4pummw).
=> [SGA] Desenvolver custom code para atribuição de chat

hubspot/custom-code/js/Client-Specific-Codes/Housi/customCreateContactByEmail.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customGetThreadContactInformations.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customGetThreadOptionsResponse.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customSendWppCSATMessage.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customSendWppOptionsToRedirect.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customSendWppWelcomeMessage.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customUpdateTicketWithCSATScore.js
Criação de um chatbot via códigos customizados em que é enviada uma mensagem de boas vindas, pedido o email e criado o contato caso não exista. Logo após esse processo, é enviada uma mensagem de redirecionamento de conversa e ao fechar a conversa é enviada uma pesquisa de CSAT e atualizado ticket com a nota dada pelo usuário.
- `hubspot/custom-code/js/Client-Specific-Codes/Housi/customCreateContactByEmail.js`: Esse código é responsável por criar um usuário caso ele não exista.
- `hubspot/custom-code/js/Client-Specific-Codes/Housi/customGetThreadContactInformations.js`: Esse código é responsável por buscar a resposta do usuário além de informações do mesmo a partir da conversa aberta.
- `hubspot/custom-code/js/Client-Specific-Codes/Housi/customGetThreadOptionsResponse.js`: Esse código foi …
=> [HOUSI] Chat Whatsapp

hubspot/custom-code/js/Client-Specific-Codes/TODOS/customMergeObjectsParceria.js
A tarefa visa mergear dois ou mais objetos quando eles possuem campos em comum mas que deveriam ser únicos. O erro é causado pela digitação errada do campo CNPJ dentro do objeto Parcerias.
-`hubspot/custom-code/js/Client-Specific-Codes/TODOS/customMergeObjectsParceria.js`: Aqui foi desenvolvido código para realizar esse merge.
Qualquer informação adicional em [análise](https://app.clickup.com/t/86a3mwjzj) e [desenvolvimento](https://app.clickup.com/t/86a3qp1xn).
=> [Desenvolvimento] Código para mesclagem de objetos com mais de 1 correspondência

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisys.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFile.js
A tarefa tem como objetivo realizar uma melhoria na coleta de dados vindos da leitura da fatura na 4docs.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisys.js`: Aqui foi alterado código para retornar exatamente o que volta da análise de crédito.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFile.js`: Aqui além de ser adicionado novos campos do retorno foi criada uma função para tornar dinâmica essa captura dos valores a partir do resultado da leitura.
Para mais informações favor consultar a [task](https://app.clickup.com/t/86a3n74jv).
=> Unidade Consumidora - API - Enviar dados de KWh (PROD)

hubspot/custom-code/js/Client-Specific-Codes/BRZ/customHS2SAP.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFile.js, hubspot/custom-code/js/Client-Specific-Codes/Printi/customHsProtheusClients.js, hubspot/custom-code/js/Client-Specific-Codes/Printi/customHsProtheusGetClient.js, hubspot/custom-code/js/Client-Specific-Codes/Printi/customHsProtheusGetProduct.js, hubspot/custom-code/js/Client-Specific-Codes/Printi/customHsProtheusOrders.js, hubspot/package.json, hubspot/yarn.lock
A atividade tem como objetivo a sincronização dos Deals criados na Hubspot serem enviados ao Protheus.
- `hubspot/custom-code/js/Client-Specific-Codes/Printi/customHsProtheusOrders.js`: Aqui foi adicionado o código referente ao commit. Foi adicionado código para envio das informações vindas de um deal criado na Hubspot ao pedido no Protheus.
Alguns arquivos foram salvos no commit mas utilizei como backup. Favor considerar somente o arquivo mencionado nas funcionalidades acima.
Qualquer outra informação adicional em [task](https://app.clickup.com/t/86a41c4pe).
=> [Desenvolvimento] Desenvolver Integração de Pedidos (Admin > HubSpot > Protheus)

hubspot/custom-code/js/Client-Specific-Codes/MAGI5/customFixHistoricalLeadStatus.js
Corrigir a base histórica de Leads, garantindo que as atividades sejam associadas ao objeto Contato, e que o lead status seja atualizado automaticamente através dos workflows configurados.
- `hubspot/custom-code/js/Client-Specific-Codes/MAGI5/customFixHistoricalLeadStatus.js`:  Código utilizado na correção histórica dos contatos criados entre 23/07 à 29/08.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a4ppuev)
=> Investigar correção da base histórica de Leads por custom code

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysParceiro.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysUC.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomLoginOnRisk3.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendAnalisysFirstUC.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendAnalisysParceiro.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendAnalisysSecondUC.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFileUC.js, hubspot/package-lock.json
A tarefa consiste em desenvolver os códigos customizados necessários para envio do CNPJ contigo no objeto Parceiro para análise na api da Risk3.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendAnalisysParceiro.js`: Código customizado que envia o CNPJ contido no Parceiro para análise.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysParceiro.js`: Código customizado que busca a análise pelo id e atualiza o objeto Parceiro caso a mesma esteja concluída.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomLoginOnRisk3.js`: Código customizado para login na Risk3.
Para qualquer informação adicional consultar [task](https://app.clickup.com/t/86a4vfuxu) e suas subtarefas.
=> [ECOM] Desenvolvimento da Solução - Análise Risk3 para objeto Parceiro.

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysParceiro.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendAnalisysParceiro.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customGetAssociatedContactInformations.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customGetOwnerEmail.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customSendZapSignParceiro.js
Tarefa [aqui](https://app.clickup.com/t/86a518r64)
=> [ECOM] Integração com ZapSign para envio de Termo de Adesão e Contrato de Parceria

hubspot/custom-code/js/Client-Specific-Codes/TODOS/customGenerateRandomNumbers.js, hubspot/custom-code/js/Client-Specific-Codes/TODOS/solutionGetContactsWithMultipleEmails.js, hubspot/winston-logger/winston.config.js
A atividade tem como objetivo sinalizar os contatos com múltiplos emails adicionais a partir de uma propriedade. Devido ao grande volume de dados lidos, foi implementada lógica pra mitigar as questões de rate limit da api da hubspot.
- `hubspot/custom-code/js/Client-Specific-Codes/TODOS/solutionGetContactsWithMultipleEmails.js`: Arquivo de lógica principal.
- `hubspot/winston-logger/winston.config.js`: Adicionada ferramente de logs para Nodejs.
Para qualquer informação adicional, verificar [tarefa](https://app.clickup.com/t/86a5pvda8)
=> [TODOS EMPREENDIMENTOS] Código de identificação de Contatos com múltiplos e-mails

hubspot/custom-code/js/Client-Specific-Codes/TODOS/customLeadsCounter.js, hubspot/custom-code/js/Client-Specific-Codes/TODOS/solutionGetContactsWithMultipleEmailsAll.js, hubspot/custom-code/js/Client-Specific-Codes/TODOS/solutionGetContactsWithMultipleEmailsWithFilter.js
Atividade (aqui)[https://app.clickup.com/t/3061382/86a5twg81]
=> [TODOS EMPREENDIMENTOS] Criação de um código de contador de leads

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysParceiro.js
Tarefa tem como objetivo retornar novas informações da API da Risk3 e popular o objeto customizado Parceiro.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetAnalisysParceiro.js`: Adicionada mais informações que retornam da Risk3.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a653xbr)
=> [ECOM] Ajuste em código customizado da API Risk 3 incluindo mais propriedades para preenchimento

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customSendFileToHubspot.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customUpdateDeal.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customUpdateParceiro.js
Essa atividade tinha como objetivo capturar a partir do webhook recebido o documento assinado e anexar a propriedade Contrato Assinado. Esse comportamento deve acontecer no fluxo de assinatura do objeto Parceiro e Deal, na jornada online.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customSendFileToHubspot.js`: Código responsável por buscar o contrato assinado e fazer o upload para a Hubspot.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customUpdateParceiro.js`: Código responsável por atualizar o Parceiro pelo seu id.
-`hubspot/custom-code/js/Client-Specific-Codes/Ecom/customUpdateDeal.js`: Código responsável por atualizar o Deal pelo seu id.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a65bnkb)
=> [ECOM] Otimização de processo integração ZapSign

hubspot/custom-code/js/Client-Specific-Codes/Jusfy/customIsOutOfOffice.js, hubspot/custom-code/js/Client-Specific-Codes/Jusfy/customSendAfkWppMessage.js
Automatizar a resposta a clientes que entrem em contato fora do SLA, garantindo que recebam uma mensagem clara sobre o funcionamento do atendimento e que sua mensagem será respondida oportunamente.
-`hubspot/custom-code/js/Client-Specific-Codes/Jusfy/customIsOutOfOffice.js`: Código que valida o horário atual no Brasil e o dia da semana de 0 a 6, sendo 0 domingo e 6 sábado.
-`hubspot/custom-code/js/Client-Specific-Codes/Jusfy/customSendAfkWppMessage.js`: Código que envia a mensagem padronizada ao cliente.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a67qqv8)
=> [JUSFY] Bot pro Whatsapp - Mensagem de Ausência

hubspot/custom-code/python/Konsi/customAddOneToCounter.py, hubspot/custom-code/python/Konsi/customAleatoryDistribution.py, hubspot/custom-code/python/Konsi/customExecutivoLimitVerify.py
Este projeto visa criar e implementar um sistema automatizado para a gestão e redistribuição de negócios com base na disponibilidade e capacidade diária dos executivos. A seguir estão os principais elementos e regras envolvidas.
-`hubspot/custom-code/python/Konsi/customAddOneToCounter.py`: Adiciona +1 ao executivo
-`hubspot/custom-code/python/Konsi/customExecutivoLimitVerify.py`: Verifica a disponibilidade do executivo selecionado
-`hubspot/custom-code/python/Konsi/customAleatoryDistribution.py`: Busca um novo executivo e seleciona aleatoriamente
Qualquer informação adicional em [task](https://app.clickup.com/t/86a685vx3)
=> [KONSI] Custom Code - Count de Proprietários

hubspot/custom-code/python/Client-Specific-Codes/CEPEL/proposalNumber.py
**Contexto**
Atualmente, o número da proposta comercial do CEPEL é preenchido manualmente utilizando um sistema externo. O objetivo deste projeto é automatizar essa geração diretamente no Hubspot, eliminando a necessidade de um sistema terceiro.
**Desenvolvimento:**
**Elementos principais:**
- Armazenamento da última proposta: Código customizado armazena na HubDB as informações do número da última proposta gerada.
- Geração incremental: O código customizado gera automaticamente o próximo número de proposta de forma sequencial.
- Atualização automática: A propriedade "Número da proposta" passa a ser preenchida sem necessidade de intervenção manual.
Link para o Workflow (Homologação)
[[Workflow]](https://app.hubspot.com/workflows/45772738/platform/flow/1628898657/edit)
Link para o …
=> [CEPEL] Preenchimento automático de numeração de proposta 

hubspot/custom-code/js/Client-Specific-Codes/Metadados/customSolucoesDoClienteCreateNewSolutionsNew.js, hubspot/custom-code/js/Client-Specific-Codes/Metadados/customSolucoesDoClienteReturnSolutionsNew.js
Esta tarefa teve como objetivo aprimorar a lógica de associação de empresas ao objeto "Soluções do Cliente", tornando o processo mais preciso e estruturado. Anteriormente, a associação era feita com base apenas na primeira ocorrência do nome da empresa, o que podia gerar inconsistências. 
- `hubspot/custom-code/js/Client-Specific-Codes/Metadados/customSolucoesDoClienteCreateNewSolutionsNew.js`: Adicionada lógica para evitar com que o id da empresa esteja em branco em caso de falha no primeiro código.
- `hubspot/custom-code/js/Client-Specific-Codes/Metadados/customSolucoesDoClienteReturnSolutionsNew.js`: Substituição do nome como chave de busca na base de dados.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a6u44xq)
=> [METADADOS] Melhoria código Soluções Clientes

hubspot/custom-code/js/Client-Specific-Codes/MA/customCadastroDeContaPFProtheus.js, hubspot/custom-code/js/Client-Specific-Codes/MA/customCadastroDeContaPJProtheus.js, hubspot/custom-code/js/Client-Specific-Codes/MA/customDealAndLineItems03Protheus.js, hubspot/custom-code/js/Reusable-Codes/customGenerateError.js
A MA Hospitalar possui integração com o sistema Protheus e necessita de um feedback mais claro para os usuários da HubSpot sobre erros ocorridos na integração. Atualmente, os erros são registrados nos logs do Workflow, sem um retorno direto ao operador. Para solucionar essa necessidade, foi sugerida a criação de uma propriedade que armazenará a mensagem de erro.
- `hubspot/custom-code/js/Reusable-Codes/customGenerateError.js`: Função para gerar erro.
- `hubspot/custom-code/js/Client-Specific-Codes/MA/customCadastroDeContaPFProtheus.js`: Adaptado tratamento de erro para não causar o erro em si, mas retornar uma propriedade com a mensagem do mesmo.
- `hubspot/custom-code/js/Client-Specific-Codes/MA/customCadastroDeContaPJProtheus.js`: Adaptado tratamento de erro para não causar o erro em …
=> [MA HOSPITALAR]  Criação de propriedade que identifique o tipo de erro ocorrido

hubspot/custom-code/python/Client-Specific-Codes/IPOG/Sympla-Integration/Wokflow2.py, hubspot/custom-code/python/Client-Specific-Codes/IPOG/Sympla-Integration/Workflow1.py, hubspot/custom-code/python/Client-Specific-Codes/IPOG/SymplaIntegration.py
Este documento detalha a solução de integração entre a plataforma Sympla e o HubSpot CRM, desenvolvida para automatizar a importação de participantes de eventos para a base de contatos do HubSpot. A solução foi projetada como uma sequência de workflows no HubSpot que respeitam as limitações de tempo de execução de 20 segundos, processando grandes volumes de dados de forma segmentada.
A integração é composta por dois workflows principais que trabalham em cascata:
- Responsável por extrair a lista de eventos ativos da Sympla.
- Retorna uma lista de eventos para processamento no próximo workflow.
- Processa um ou mais eventos por vez, com controle de tempo.
- Extrai participantes e enriquece com dados de pedidos.
- Mapeia dados para o formato do HubSpot.
- Processa lotes de contatos via API …
=> [IPOG] Integração Sympla <> HubSpot

hubspot/custom-code/python/utils/duplicate-contacts-analysis/DB_ContatoDuplicado.py, hubspot/custom-code/python/utils/duplicate-contacts-analysis/EXCEL_ContactsDuplicated.py, hubspot/custom-code/python/utils/duplicate-contacts-analysis/README.md
Conclusão da Tarefa:
Conforme alinhado anteriormente, estamos finalizando a task de identificação de contatos duplicados. Para essa atividade, foram desenvolvidos dois códigos reutilizáveis, que podem ser executados fora do HubSpot e adaptados para outras necessidades semelhantes.
Código 1
Realiza a extração de contatos e armazena os dados em um arquivo Excel. Em seguida, processa essas informações para identificar contatos duplicados com base em e-mail, nome e telefone, além de apontar registros com campos em branco (e-mail, nome e telefone).
- Limite de contatos: até 1 milhão.
Código 2
Executa a extração e armazena os contatos em um banco de dados. Possui a mesma lógica de identificação de duplicidades e campos em branco que o Código 1, porém foi desenvolvido para suportar grandes …
=> Duplicate Contacts analysis

hubspot/custom-code/python/Client-Specific-Codes/IPOG/IPOG_CURSOS.py
Foi criado um script que identifica um curso a partir de das propriedades:
- `recent_conversion_event_name`
- `curso_de_interesse`
Esses campos são comparados com os cursos disponíveis na API do IPOG (`https://api-newams.ipog.edu.br/cursos`).  
Se houver correspondência, as principais informações do curso são retornadas.
---
1. Lê os campos de entrada (`recent_conversion_event_name` e `curso_de_interesse`).
2. Consulta a API de cursos do IPOG.
3. Compara os termos com o nome e o slug dos cursos.
4. Se encontrar um curso, retorna:
- `curso_id`
- `curso_id_crm`
- `tipo_de_ensino_slug`
- `tipo_de_formacao_slug`
- `Área de Atuação`
5. Se não encontrar, retorna esses campos com valor `None`.
---
```json
{
"curso_id": 123,
"curso_id_crm": "333",
"tipo_de_ensino_slug": "ead", …
```
=> [IPOG] Solução para WF de conversão | Workflow com + de 1000 ações

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFileUC.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomUpdateUCByWebhook.js
Substituir a atual API da 4docs, responsável pela extração de dados das faturas das Unidades Consumidoras, pela nova API própria da ECOM, que realiza o mesmo processo utilizando inteligência artificial. A principal mudança no fluxo é a substituição da resposta direta da API pela recepção dos dados via webhook.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomUpdateUCByWebhook.js`: Código que recebe os dados do webhook e atualiza a UC.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomSendFileUC.js`: Substituição da 4docs pela chamada da IA.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a80bvm0)
=> [ECOM] Trocar API leitura de fatura (4docs) por IA da ecom com cod customizado

hubspot/custom-code/python/Client-Specific-Codes/ARMAC/AssociateLineItems.py, hubspot/custom-code/python/Client-Specific-Codes/ARMAC/dataModelinForLineItemsg.py
Implementar um **Custom Code na ARMAC** para processar solicitações de equipamentos (compra de seminovos ou locação). O código identifica os itens solicitados, busca produtos correspondentes no catálogo da HubSpot e cria automaticamente line items associados ao deal. Esta automação elimina a necessidade de entrada manual de dados, reduz erros operacionais e garante consistência na gestão de pedidos.
---
A solução é composta por dois módulos sequenciais:
- **Detecção do Tipo de Processo**  
Identifica automaticamente se a solicitação é para **locação** ou **compra de seminovos**, baseado nas propriedades preenchidas.
- **Normalização de Dados**  
- Para **locação**: processa o campo `equipamentos_e_quantidades_solicitados` (texto multilinha no formato `"QUANTIDADE - EQUIPAMENTO"`).  
- …
=> [ARMAC] Desenvolvimento da Automação de Itens de Linha

hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomCreateMigration.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetMigrationCardAndUpdateUC.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomMigrationAuth.js, hubspot/custom-code/js/Client-Specific-Codes/Ecom/customGetAssociatedContactEmail.js, hubspot/custom-code/js/Client-Specific-Codes/Housi/customMapTicketsProperties.js
Desenvolver códigos que conectem a HubSpot ao sistema de Migração Simplificada para envio e recebimento de dados.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomMigrationAuth.js`: Código de autenticação à API de migração.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customGetAssociatedContactEmail.js`: Código que busca o contato associado ao Negócio que por sua vez está associado à Unidade Consumidora.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomCreateMigration.js`: Código para criação de uma solicitação de migração.
- `hubspot/custom-code/js/Client-Specific-Codes/Ecom/customEcomGetMigrationCardAndUpdateUC.js`: Código que busca o card de migração e atualiza a Unidade Consumidora.
Qualquer informação adicional em …
=> [ECOM] Integração API Migração Simplificada

hubspot/custom-code/js/Client-Specific-Codes/TODOS/customDeleteDeal.js
Automatizar a exclusão de negócios que permanecerem inativos por 30 dias, com o objetivo de manter a base limpa e atualizada.
- `hubspot/custom-code/js/Client-Specific-Codes/TODOS/customDeleteDeal.js`: Código para exclusão de deal.
Qualquer informação adicional em [task](https://app.clickup.com/t/86a9ap4ev)
=> [Todos Empreendimentos] Código de exclusão automática de negócios.

hubspot/custom-code/python/Client-Specific-Codes/IPOG/Sympla-Integration/Wokflow2.py
feat(ipog-sympla): add email validation and deduplication in batch processing
- Implement regex-based email validation for Brazilian domains
- Add email deduplication to prevent duplicate contacts in batches
- Optimize batch processing by filtering out invalid entries
task: https://app.clickup.com/t/86a9p3hvx
=> feat: add email validation and deduplication for IPOG Sympla integration
